"""empty message

Revision ID: f9a11611f94c
Revises: 4ac993c92754
Create Date: 2023-05-20 12:52:01.035384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a11611f94c'
down_revision = '4ac993c92754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country_neighbour', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'country_neighbour', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country_neighbour', type_='foreignkey')
    op.drop_column('country_neighbour', 'country_id')
    # ### end Alembic commands ###
